#!/usr/bin/env bash
# set up an nginx server

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
