#!/usr/bin/env bash
# set up an nginx server

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo /etc/init.d/nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx restart
