#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y upgrade

sudo sed -i '/listen 80 default_server;/a add_header X-Served-By ${HOSTNAME};' /etc/nginx/sites-available/default

sudo service nginx restart
