#!/usr/bin/env bash
# installs the load balancer HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy
sudo echo "
frontend web-fronted
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 1834-web-01 3.91.58.19 check
        server 1834-web-02 52.90.163.135 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
