#!/usr/bin/env bash
# installs the load balancer HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

inst="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\nbackend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 3.91.58.19:80 check
\n\tserver web-02 52.90.163.135:80 check"

echo -e "$inst" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c

sudo service haproxy restart
